strategy:
  matrix:
    linux_node12:
      imageName: 'ubuntu-16.04'
      node_version: 12.x
    linux_node10:
      imageName: 'ubuntu-16.04'
      node_version: 10.x
    linux_node8:
      imageName: 'ubuntu-16.04'
      node_version: 8.x

pool:
  vmImage: $(imageName)

resources:
  containers:
  - container: redis
    image: redis
    ports:
    - 6379:6379

services:
  redis: redis

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- bash: npm install
  displayName: install

- bash: npm test
  displayName: test

- bash: npm run lint
  displayName: lint
