name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    strategy:
      matrix:
        node: [10, 12, 14]
    # must use Linux for redis container
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-redis-service-containers
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
